#Demo Project Application

trigger:
- Master

pool:
  vmImage: ubuntu-latest

stages:
  - stage: 'junit'
    displayName: 'junit Stage'
    jobs:
     - job: 'junitTest'
       displayName: 'Running unit tests'
       steps:
        - script: echo 'Running Spring demo project unit test'
        - task: Npm@1
          inputs:
            command: 'install'
            workingDir: '/TaskDirectory'
            




  