#Demo Project Application

trigger:
- Master

pool:
  vmImage: ubuntu-latest


steps:
# ...
# do this after other tasks such as building
- task: DotNetCoreCLI@2
  inputs:
    command: test
    projects: '**/*Tests/*.csproj'
    arguments: '--configuration $(buildConfiguration)'





  