#Demo Project Application

trigger:
- Master

pool:
  vmImage: ubuntu-latest

stages:
  - stage: 'junit'
    displayName: 'junit Stage'
    jobs:
     - job: 'junitTest'
       displayName: 'Running unit tests'
       steps:
        - template: PracticeProject.csproj
            




  