#Demo Project Application

trigger:
- Master

pool:
  vmImage: ubuntu-latest

stages:
  - stage: 'junit'
    displayName: 'junit Stage'
    jobs:
     - job: 'junitTest'
       displayName: 'Running unit tests'
       steps:
        - task: DotNetCoreCLI@0
          inputs:
              command: 'build'
              projects: '**/*Tests/*.csproj'
              arguments: '--configuration $(buildConfiguration)'




  